# Generated by Django 3.2.16 on 2022-12-18 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=60, verbose_name='RUC')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre y apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('price', models.FloatField(verbose_name='Precio de venta')),
                ('stocks', models.IntegerField(verbose_name='Existencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocks', models.IntegerField(verbose_name='Existencia')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='Total')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.product', verbose_name='Producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha de venta')),
                ('invoice', models.CharField(max_length=60, verbose_name='Número de factura')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsales', to='core.client', verbose_name='Cliente')),
                ('products', models.ManyToManyField(related_name='products', through='core.ProductDetail', to='core.Product', verbose_name='Productos')),
            ],
            options={
                'verbose_name': 'Venta de productos',
                'verbose_name_plural': 'Venta de productos',
            },
        ),
        migrations.AddField(
            model_name='productdetail',
            name='product_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.productsale', verbose_name='Venta de producto'),
        ),
    ]
