# Generated by Django 3.2.16 on 2022-12-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='productdetail',
            options={'verbose_name': 'Detalle de producto', 'verbose_name_plural': 'Detalle de productos'},
        ),
        migrations.AlterField(
            model_name='productsale',
            name='date',
            field=models.DateField(verbose_name='Fecha de venta'),
        ),
    ]
